export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const ITEMS_FETCH_DATA_SUCCESS = 'ITEMS_FETCH_DATA_SUCCESS';
export const ITEMS_IS_LOADING = 'ITEMS_IS_LOADING';
export const ITEMS_HAS_ERRORED = 'ITEMS_HAS_ERRORED';
export const SEND_SUBSCRIPTION = 'SEND_SUBSCRIPTION';
export const SUBMIT = 'SUBMIT';
